name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarQubeScan:
    name: Run SonarQube Scan1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install SonarQube Scanner
        run: npm install -g sonar-scanner

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
