name: SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: sonar  # This makes sure the build job waits for the sonar job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Build
        run: npm install
          # Add your build commands here
          echo "Building the project..."
